- name: copy mongo repo
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: clean yum cache
  command: yum clean all

- name: make cache
  command: yum makecache

- name: install mongodb-org
  yum:
    name: mongodb-org
    state: present